Return-Path: <devel-bounces@acpica.org>
X-Original-To: lists+devel-acpica@lfdr.de
Delivered-To: lists+devel-acpica@lfdr.de
Received: from ml01.01.org (ml01.01.org [198.145.21.10])
	by mail.lfdr.de (Postfix) with ESMTPS id F28B74E96A9
	for <lists+devel-acpica@lfdr.de>; Mon, 28 Mar 2022 14:33:49 +0200 (CEST)
Received: from ml01.vlan13.01.org (localhost [IPv6:::1])
	by ml01.01.org (Postfix) with ESMTP id 1ACCB100F392B;
	Mon, 28 Mar 2022 05:33:48 -0700 (PDT)
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=209.85.219.179; helo=mail-yb1-f179.google.com; envelope-from=rjwysocki@gmail.com; receiver=<UNKNOWN> 
Received: from mail-yb1-f179.google.com (mail-yb1-f179.google.com [209.85.219.179])
	(using TLSv1.3 with cipher TLS_AES_128_GCM_SHA256 (128/128 bits))
	(No client certificate requested)
	by ml01.01.org (Postfix) with ESMTPS id 2EACD100F3928
	for <devel@acpica.org>; Mon, 28 Mar 2022 05:33:46 -0700 (PDT)
Received: by mail-yb1-f179.google.com with SMTP id y142so25671265ybe.11
        for <devel@acpica.org>; Mon, 28 Mar 2022 05:33:46 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112;
        h=x-gm-message-state:mime-version:references:in-reply-to:from:date
         :message-id:subject:to:cc:content-transfer-encoding;
        bh=96R3YZlaxPkbqjS50KOs84E9IviQBiQAWcWza7S6bDo=;
        b=dSKGnn6K34lqRSXA2W9QhnTSLh6V2OQH4PV3wLF6FktvOnFaVVchD+2dGVBBGdIEOP
         76Cr4Bc/0dmhtqiINnzlwJZU/XXPw22quAz4YUfzEkHVQXdRNrL/3tgvmIvtQE1FrFVB
         xHCeVj1iPj2v6Bj+F9pFFM04DT1eyxMAk6roe4rx3RmL0slBSo1xt7LXz6EMD18ZMgXv
         ezXd0GveHpzqaBDCjlUsB5CS7IAD3PNcSO0dlvSuyTgbJqIj2l1jB1N80KZgKuXwjSri
         3ysoGZ6z/X3kuB1aDLGDq72Xh3saaEhtC6WiaPISWeaDyg36gPsUrHeSO7DDmLfYPimQ
         ESbQ==
X-Gm-Message-State: AOAM531zkkd/fW77V13fAfWE4hU0do0ZtfimmpUwkvLQmGy61S2uSKPY
	VdCPC9FWgjsFmzgQg3ej8K8LFbtyL5j8IfkDouE=
X-Google-Smtp-Source: ABdhPJx8Wg38N6VDkBqHhGiMOIVXRrg4vGvCYLhNlosUsWn6MZ6VqGYcxoBV2Rzxwr0C4NFzPtT0Oq2lDLGzpa8RiBA=
X-Received: by 2002:a25:9d8a:0:b0:633:9668:c48a with SMTP id
 v10-20020a259d8a000000b006339668c48amr23154148ybp.153.1648470824874; Mon, 28
 Mar 2022 05:33:44 -0700 (PDT)
MIME-Version: 1.0
References: <20220326165909.506926-1-benni@stuerz.xyz> <20220326165909.506926-5-benni@stuerz.xyz>
In-Reply-To: <20220326165909.506926-5-benni@stuerz.xyz>
From: "Rafael J. Wysocki" <rafael@kernel.org>
Date: Mon, 28 Mar 2022 14:33:29 +0200
Message-ID: <CAJZ5v0iJ=t26mnxHx9B+_A3ue7tVjgATN=TTtNNf2UNfuySd7Q@mail.gmail.com>
To: =?UTF-8?Q?Benjamin_St=C3=BCrz?= <benni@stuerz.xyz>
Message-ID-Hash: KBW3OJWG6GHQDLU6ZPDJK3U53I36GUFY
X-Message-ID-Hash: KBW3OJWG6GHQDLU6ZPDJK3U53I36GUFY
X-MailFrom: rjwysocki@gmail.com
X-Mailman-Rule-Hits: nonmember-moderation
X-Mailman-Rule-Misses: dmarc-mitigation; no-senders; approved; emergency; loop; banned-address; member-moderation
CC: Andrew Lunn <andrew@lunn.ch>, Sebastian Hesselbarth <sebastian.hesselbarth@gmail.com>, Gregory Clement <gregory.clement@bootlin.com>, Russell King - ARM Linux <linux@armlinux.org.uk>, linux@simtec.co.uk, Krzysztof Kozlowski <krzk@kernel.org>, Alim Akhtar <alim.akhtar@samsung.com>, Thomas Gleixner <tglx@linutronix.de>, Ingo Molnar <mingo@redhat.com>, Borislav Petkov <bp@alien8.de>, Dave Hansen <dave.hansen@linux.intel.com>, "H. Peter Anvin" <hpa@zytor.com>, Rafael Wysocki <rafael.j.wysocki@intel.com>, 3chas3@gmail.com, laforge@gnumonks.org, Arnd Bergmann <arnd@arndb.de>, Greg Kroah-Hartman <gregkh@linuxfoundation.org>, Mauro Carvalho Chehab <mchehab@kernel.org>, Tony Luck <tony.luck@intel.com>, Robert Richter <rric@kernel.org>, Linus Walleij <linus.walleij@linaro.org>, Bartosz Golaszewski <brgl@bgdev.pl>, mike.marciniszyn@cornelisnetworks.com, dennis.dalessandro@cornelisnetworks.com, Jason Gunthorpe <jgg@ziepe.ca>, =?UTF-8?Q?Pali_Roh=C3=A1r?= <pali@kernel.org>, Dmitry Torokhov <dm
 itry.torokhov@gmail.com>, isdn@linux-pingi.de, Benjamin Herrenschmidt <benh@kernel.crashing.org>, Frederic Barrat <fbarrat@linux.ibm.com>, Andrew Donnellan <ajd@linux.ibm.com>, David Miller <davem@davemloft.net>, Jakub Kicinski <kuba@kernel.org>, pabeni@redhat.com, Nicolas Pitre <nico@fluxnic.net>, Loic Poulain <loic.poulain@linaro.org>, kvalo@kernel.org, pkshih@realtek.com, Bjorn Helgaas <bhelgaas@google.com>, Linux ARM <linux-arm-kernel@lists.infradead.org>, Linux Kernel Mailing List <linux-kernel@vger.kernel.org>, Linux Samsung SoC <linux-samsung-soc@vger.kernel.org>, linux-ia64@vger.kernel.org, ACPI Devel Maling List <linux-acpi@vger.kernel.org>, "open list:ACPI COMPONENT ARCHITECTURE (ACPICA)" <devel@acpica.org>, linux-atm-general@lists.sourceforge.net, netdev <netdev@vger.kernel.org>, "open list:EDAC-CORE" <linux-edac@vger.kernel.org>, "open list:GPIO SUBSYSTEM" <linux-gpio@vger.kernel.org>, linux-rdma@vger.kernel.org, linux-input <linux-input@vger.kernel.org>, linuxppc-dev <l
 inuxppc-dev@lists.ozlabs.org>, Linux Media Mailing List <linux-media@vger.kernel.org>, wcn36xx@lists.infradead.org, "open list:NETWORKING DRIVERS (WIRELESS)" <linux-wireless@vger.kernel.org>, Linux PCI <linux-pci@vger.kernel.org>
X-Mailman-Version: 3.1.1
Precedence: list
Subject: [Devel] Re: [PATCH 05/22] acpica: Replace comments with C99 initializers
List-Id: ACPICA Developer Mailing List <devel.acpica.org>
Archived-At: <https://lists.acpica.org/hyperkitty/list/devel@acpica.org/message/KBW3OJWG6GHQDLU6ZPDJK3U53I36GUFY/>
List-Archive: <https://lists.acpica.org/hyperkitty/list/devel@acpica.org/>
List-Help: <mailto:devel-request@acpica.org?subject=help>
List-Post: <mailto:devel@acpica.org>
List-Subscribe: <mailto:devel-join@acpica.org>
List-Unsubscribe: <mailto:devel-leave@acpica.org>
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64

T24gU2F0LCBNYXIgMjYsIDIwMjIgYXQgNjowOSBQTSBCZW5qYW1pbiBTdMO8cnogPGJlbm5pQHN0
dWVyei54eXo+IHdyb3RlOg0KPg0KPiBUaGlzIHJlcGxhY2VzIGNvbW1lbnRzIHdpdGggQzk5J3Mg
ZGVzaWduYXRlZA0KPiBpbml0aWFsaXplcnMgYmVjYXVzZSB0aGUga2VybmVsIHN1cHBvcnRzIHRo
ZW0gbm93Lg0KDQpIb3dldmVyLCBub3RlIHRoYXQgYWxsIG9mIHRoZSBBQ1BJQ0EgbWF0ZXJpYWwg
c2hvdWxkIGJlIHN1Ym1pdHRlZCB0bw0KdGhlIHVwc3RyZWFtIEFDUElDQSBwcm9qZWN0IHZpYSBo
dHRwczovL2dpdGh1Yi5jb20vYWNwaWNhL2FjcGljYQ0KDQpBbHNvIHBsZWFzZSBub3RlIHRoYXQg
dGhlIHNldCBvZiBjb21waWxlcnMgdGhhdCBuZWVkIHRvIGJlIHN1cHBvcnRlZA0KYnkgdGhlIEFD
UElDQSBwcm9qZWN0IGlzIGdyZWF0ZXIgdGhhbiB0aGUgc2V0IG9mIGNvbXBpbGVycyB0aGF0IGNh
bg0KYnVpbGQgdGhlIExpbnV4IGtlcm5lbC4NCg0KDQo+IFNpZ25lZC1vZmYtYnk6IEJlbmphbWlu
IFN0w7xyeiA8YmVubmlAc3R1ZXJ6Lnh5ej4NCj4gLS0tDQo+ICBkcml2ZXJzL2FjcGkvYWNwaWNh
L3V0ZGVjb2RlLmMgfCAxODMgKysrKysrKysrKysrKysrKy0tLS0tLS0tLS0tLS0tLS0tDQo+ICAx
IGZpbGUgY2hhbmdlZCwgOTAgaW5zZXJ0aW9ucygrKSwgOTMgZGVsZXRpb25zKC0pDQo+DQo+IGRp
ZmYgLS1naXQgYS9kcml2ZXJzL2FjcGkvYWNwaWNhL3V0ZGVjb2RlLmMgYi9kcml2ZXJzL2FjcGkv
YWNwaWNhL3V0ZGVjb2RlLmMNCj4gaW5kZXggYmNkMzg3MTA3OWQ3Li5kMTk4NjhkMmVhNDYgMTAw
NjQ0DQo+IC0tLSBhL2RyaXZlcnMvYWNwaS9hY3BpY2EvdXRkZWNvZGUuYw0KPiArKysgYi9kcml2
ZXJzL2FjcGkvYWNwaWNhL3V0ZGVjb2RlLmMNCj4gQEAgLTE1NiwzNyArMTU2LDM3IEBAIHN0YXRp
YyBjb25zdCBjaGFyIGFjcGlfZ2JsX2JhZF90eXBlW10gPSAiVU5ERUZJTkVEIjsNCj4gIC8qIFBy
aW50YWJsZSBuYW1lcyBvZiB0aGUgQUNQSSBvYmplY3QgdHlwZXMgKi8NCj4NCj4gIHN0YXRpYyBj
b25zdCBjaGFyICphY3BpX2dibF9uc190eXBlX25hbWVzW10gPSB7DQo+IC0gICAgICAgLyogMDAg
Ki8gIlVudHlwZWQiLA0KPiAtICAgICAgIC8qIDAxICovICJJbnRlZ2VyIiwNCj4gLSAgICAgICAv
KiAwMiAqLyAiU3RyaW5nIiwNCj4gLSAgICAgICAvKiAwMyAqLyAiQnVmZmVyIiwNCj4gLSAgICAg
ICAvKiAwNCAqLyAiUGFja2FnZSIsDQo+IC0gICAgICAgLyogMDUgKi8gIkZpZWxkVW5pdCIsDQo+
IC0gICAgICAgLyogMDYgKi8gIkRldmljZSIsDQo+IC0gICAgICAgLyogMDcgKi8gIkV2ZW50IiwN
Cj4gLSAgICAgICAvKiAwOCAqLyAiTWV0aG9kIiwNCj4gLSAgICAgICAvKiAwOSAqLyAiTXV0ZXgi
LA0KPiAtICAgICAgIC8qIDEwICovICJSZWdpb24iLA0KPiAtICAgICAgIC8qIDExICovICJQb3dl
ciIsDQo+IC0gICAgICAgLyogMTIgKi8gIlByb2Nlc3NvciIsDQo+IC0gICAgICAgLyogMTMgKi8g
IlRoZXJtYWwiLA0KPiAtICAgICAgIC8qIDE0ICovICJCdWZmZXJGaWVsZCIsDQo+IC0gICAgICAg
LyogMTUgKi8gIkRkYkhhbmRsZSIsDQo+IC0gICAgICAgLyogMTYgKi8gIkRlYnVnT2JqZWN0IiwN
Cj4gLSAgICAgICAvKiAxNyAqLyAiUmVnaW9uRmllbGQiLA0KPiAtICAgICAgIC8qIDE4ICovICJC
YW5rRmllbGQiLA0KPiAtICAgICAgIC8qIDE5ICovICJJbmRleEZpZWxkIiwNCj4gLSAgICAgICAv
KiAyMCAqLyAiUmVmZXJlbmNlIiwNCj4gLSAgICAgICAvKiAyMSAqLyAiQWxpYXMiLA0KPiAtICAg
ICAgIC8qIDIyICovICJNZXRob2RBbGlhcyIsDQo+IC0gICAgICAgLyogMjMgKi8gIk5vdGlmeSIs
DQo+IC0gICAgICAgLyogMjQgKi8gIkFkZHJIYW5kbGVyIiwNCj4gLSAgICAgICAvKiAyNSAqLyAi
UmVzb3VyY2VEZXNjIiwNCj4gLSAgICAgICAvKiAyNiAqLyAiUmVzb3VyY2VGbGQiLA0KPiAtICAg
ICAgIC8qIDI3ICovICJTY29wZSIsDQo+IC0gICAgICAgLyogMjggKi8gIkV4dHJhIiwNCj4gLSAg
ICAgICAvKiAyOSAqLyAiRGF0YSIsDQo+IC0gICAgICAgLyogMzAgKi8gIkludmFsaWQiDQo+ICsg
ICAgICAgWzBdICA9ICJVbnR5cGVkIiwNCj4gKyAgICAgICBbMV0gID0gIkludGVnZXIiLA0KPiAr
ICAgICAgIFsyXSAgPSAiU3RyaW5nIiwNCj4gKyAgICAgICBbM10gID0gIkJ1ZmZlciIsDQo+ICsg
ICAgICAgWzRdICA9ICJQYWNrYWdlIiwNCj4gKyAgICAgICBbNV0gID0gIkZpZWxkVW5pdCIsDQo+
ICsgICAgICAgWzZdICA9ICJEZXZpY2UiLA0KPiArICAgICAgIFs3XSAgPSAiRXZlbnQiLA0KPiAr
ICAgICAgIFs4XSAgPSAiTWV0aG9kIiwNCj4gKyAgICAgICBbOV0gID0gIk11dGV4IiwNCj4gKyAg
ICAgICBbMTBdID0gIlJlZ2lvbiIsDQo+ICsgICAgICAgWzExXSA9ICJQb3dlciIsDQo+ICsgICAg
ICAgWzEyXSA9ICJQcm9jZXNzb3IiLA0KPiArICAgICAgIFsxM10gPSAiVGhlcm1hbCIsDQo+ICsg
ICAgICAgWzE0XSA9ICJCdWZmZXJGaWVsZCIsDQo+ICsgICAgICAgWzE1XSA9ICJEZGJIYW5kbGUi
LA0KPiArICAgICAgIFsxNl0gPSAiRGVidWdPYmplY3QiLA0KPiArICAgICAgIFsxN10gPSAiUmVn
aW9uRmllbGQiLA0KPiArICAgICAgIFsxOF0gPSAiQmFua0ZpZWxkIiwNCj4gKyAgICAgICBbMTld
ID0gIkluZGV4RmllbGQiLA0KPiArICAgICAgIFsyMF0gPSAiUmVmZXJlbmNlIiwNCj4gKyAgICAg
ICBbMjFdID0gIkFsaWFzIiwNCj4gKyAgICAgICBbMjJdID0gIk1ldGhvZEFsaWFzIiwNCj4gKyAg
ICAgICBbMjNdID0gIk5vdGlmeSIsDQo+ICsgICAgICAgWzI0XSA9ICJBZGRySGFuZGxlciIsDQo+
ICsgICAgICAgWzI1XSA9ICJSZXNvdXJjZURlc2MiLA0KPiArICAgICAgIFsyNl0gPSAiUmVzb3Vy
Y2VGbGQiLA0KPiArICAgICAgIFsyN10gPSAiU2NvcGUiLA0KPiArICAgICAgIFsyOF0gPSAiRXh0
cmEiLA0KPiArICAgICAgIFsyOV0gPSAiRGF0YSIsDQo+ICsgICAgICAgWzMwXSA9ICJJbnZhbGlk
Ig0KPiAgfTsNCj4NCj4gIGNvbnN0IGNoYXIgKmFjcGlfdXRfZ2V0X3R5cGVfbmFtZShhY3BpX29i
amVjdF90eXBlIHR5cGUpDQo+IEBAIC0yODQsMjIgKzI4NCwyMiBAQCBjb25zdCBjaGFyICphY3Bp
X3V0X2dldF9ub2RlX25hbWUodm9pZCAqb2JqZWN0KQ0KPiAgLyogUHJpbnRhYmxlIG5hbWVzIG9m
IG9iamVjdCBkZXNjcmlwdG9yIHR5cGVzICovDQo+DQo+ICBzdGF0aWMgY29uc3QgY2hhciAqYWNw
aV9nYmxfZGVzY190eXBlX25hbWVzW10gPSB7DQo+IC0gICAgICAgLyogMDAgKi8gIk5vdCBhIERl
c2NyaXB0b3IiLA0KPiAtICAgICAgIC8qIDAxICovICJDYWNoZWQgT2JqZWN0IiwNCj4gLSAgICAg
ICAvKiAwMiAqLyAiU3RhdGUtR2VuZXJpYyIsDQo+IC0gICAgICAgLyogMDMgKi8gIlN0YXRlLVVw
ZGF0ZSIsDQo+IC0gICAgICAgLyogMDQgKi8gIlN0YXRlLVBhY2thZ2UiLA0KPiAtICAgICAgIC8q
IDA1ICovICJTdGF0ZS1Db250cm9sIiwNCj4gLSAgICAgICAvKiAwNiAqLyAiU3RhdGUtUm9vdFBh
cnNlU2NvcGUiLA0KPiAtICAgICAgIC8qIDA3ICovICJTdGF0ZS1QYXJzZVNjb3BlIiwNCj4gLSAg
ICAgICAvKiAwOCAqLyAiU3RhdGUtV2Fsa1Njb3BlIiwNCj4gLSAgICAgICAvKiAwOSAqLyAiU3Rh
dGUtUmVzdWx0IiwNCj4gLSAgICAgICAvKiAxMCAqLyAiU3RhdGUtTm90aWZ5IiwNCj4gLSAgICAg
ICAvKiAxMSAqLyAiU3RhdGUtVGhyZWFkIiwNCj4gLSAgICAgICAvKiAxMiAqLyAiVHJlZSBXYWxr
IFN0YXRlIiwNCj4gLSAgICAgICAvKiAxMyAqLyAiUGFyc2UgVHJlZSBPcCIsDQo+IC0gICAgICAg
LyogMTQgKi8gIk9wZXJhbmQgT2JqZWN0IiwNCj4gLSAgICAgICAvKiAxNSAqLyAiTmFtZXNwYWNl
IE5vZGUiDQo+ICsgICAgICAgWzBdICA9ICJOb3QgYSBEZXNjcmlwdG9yIiwNCj4gKyAgICAgICBb
MV0gID0gIkNhY2hlZCBPYmplY3QiLA0KPiArICAgICAgIFsyXSAgPSAiU3RhdGUtR2VuZXJpYyIs
DQo+ICsgICAgICAgWzNdICA9ICJTdGF0ZS1VcGRhdGUiLA0KPiArICAgICAgIFs0XSAgPSAiU3Rh
dGUtUGFja2FnZSIsDQo+ICsgICAgICAgWzVdICA9ICJTdGF0ZS1Db250cm9sIiwNCj4gKyAgICAg
ICBbNl0gID0gIlN0YXRlLVJvb3RQYXJzZVNjb3BlIiwNCj4gKyAgICAgICBbN10gID0gIlN0YXRl
LVBhcnNlU2NvcGUiLA0KPiArICAgICAgIFs4XSAgPSAiU3RhdGUtV2Fsa1Njb3BlIiwNCj4gKyAg
ICAgICBbOV0gID0gIlN0YXRlLVJlc3VsdCIsDQo+ICsgICAgICAgWzEwXSA9ICJTdGF0ZS1Ob3Rp
ZnkiLA0KPiArICAgICAgIFsxMV0gPSAiU3RhdGUtVGhyZWFkIiwNCj4gKyAgICAgICBbMTJdID0g
IlRyZWUgV2FsayBTdGF0ZSIsDQo+ICsgICAgICAgWzEzXSA9ICJQYXJzZSBUcmVlIE9wIiwNCj4g
KyAgICAgICBbMTRdID0gIk9wZXJhbmQgT2JqZWN0IiwNCj4gKyAgICAgICBbMTVdID0gIk5hbWVz
cGFjZSBOb2RlIg0KPiAgfTsNCj4NCj4gIGNvbnN0IGNoYXIgKmFjcGlfdXRfZ2V0X2Rlc2NyaXB0
b3JfbmFtZSh2b2lkICpvYmplY3QpDQo+IEBAIC0zMzEsMTMgKzMzMSwxMyBAQCBjb25zdCBjaGFy
ICphY3BpX3V0X2dldF9kZXNjcmlwdG9yX25hbWUodm9pZCAqb2JqZWN0KQ0KPiAgLyogUHJpbnRh
YmxlIG5hbWVzIG9mIHJlZmVyZW5jZSBvYmplY3Qgc3ViLXR5cGVzICovDQo+DQo+ICBzdGF0aWMg
Y29uc3QgY2hhciAqYWNwaV9nYmxfcmVmX2NsYXNzX25hbWVzW10gPSB7DQo+IC0gICAgICAgLyog
MDAgKi8gIkxvY2FsIiwNCj4gLSAgICAgICAvKiAwMSAqLyAiQXJndW1lbnQiLA0KPiAtICAgICAg
IC8qIDAyICovICJSZWZPZiIsDQo+IC0gICAgICAgLyogMDMgKi8gIkluZGV4IiwNCj4gLSAgICAg
ICAvKiAwNCAqLyAiRGRiSGFuZGxlIiwNCj4gLSAgICAgICAvKiAwNSAqLyAiTmFtZWQgT2JqZWN0
IiwNCj4gLSAgICAgICAvKiAwNiAqLyAiRGVidWciDQo+ICsgICAgICAgWzBdID0gIkxvY2FsIiwN
Cj4gKyAgICAgICBbMV0gPSAiQXJndW1lbnQiLA0KPiArICAgICAgIFsyXSA9ICJSZWZPZiIsDQo+
ICsgICAgICAgWzNdID0gIkluZGV4IiwNCj4gKyAgICAgICBbNF0gPSAiRGRiSGFuZGxlIiwNCj4g
KyAgICAgICBbNV0gPSAiTmFtZWQgT2JqZWN0IiwNCj4gKyAgICAgICBbNl0gPSAiRGVidWciDQo+
ICB9Ow0KPg0KPiAgY29uc3QgY2hhciAqYWNwaV91dF9nZXRfcmVmZXJlbmNlX25hbWUodW5pb24g
YWNwaV9vcGVyYW5kX29iamVjdCAqb2JqZWN0KQ0KPiBAQCAtNDE2LDI1ICs0MTYsMjIgQEAgY29u
c3QgY2hhciAqYWNwaV91dF9nZXRfbXV0ZXhfbmFtZSh1MzIgbXV0ZXhfaWQpDQo+ICAvKiBOYW1l
cyBmb3IgTm90aWZ5KCkgdmFsdWVzLCB1c2VkIGZvciBkZWJ1ZyBvdXRwdXQgKi8NCj4NCj4gIHN0
YXRpYyBjb25zdCBjaGFyICphY3BpX2dibF9nZW5lcmljX25vdGlmeVtBQ1BJX0dFTkVSSUNfTk9U
SUZZX01BWCArIDFdID0gew0KPiAtICAgICAgIC8qIDAwICovICJCdXMgQ2hlY2siLA0KPiAtICAg
ICAgIC8qIDAxICovICJEZXZpY2UgQ2hlY2siLA0KPiAtICAgICAgIC8qIDAyICovICJEZXZpY2Ug
V2FrZSIsDQo+IC0gICAgICAgLyogMDMgKi8gIkVqZWN0IFJlcXVlc3QiLA0KPiAtICAgICAgIC8q
IDA0ICovICJEZXZpY2UgQ2hlY2sgTGlnaHQiLA0KPiAtICAgICAgIC8qIDA1ICovICJGcmVxdWVu
Y3kgTWlzbWF0Y2giLA0KPiAtICAgICAgIC8qIDA2ICovICJCdXMgTW9kZSBNaXNtYXRjaCIsDQo+
IC0gICAgICAgLyogMDcgKi8gIlBvd2VyIEZhdWx0IiwNCj4gLSAgICAgICAvKiAwOCAqLyAiQ2Fw
YWJpbGl0aWVzIENoZWNrIiwNCj4gLSAgICAgICAvKiAwOSAqLyAiRGV2aWNlIFBMRCBDaGVjayIs
DQo+IC0gICAgICAgLyogMEEgKi8gIlJlc2VydmVkIiwNCj4gLSAgICAgICAvKiAwQiAqLyAiU3lz
dGVtIExvY2FsaXR5IFVwZGF0ZSIsDQo+IC0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAvKiAwQyAqLyAiUmVzZXJ2ZWQgKHdhcyBw
cmV2aW91c2x5IFNodXRkb3duIFJlcXVlc3QpIiwNCj4gLSAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC8qIFJlc2VydmVkIGluIEFD
UEkgNi4wICovDQo+IC0gICAgICAgLyogMEQgKi8gIlN5c3RlbSBSZXNvdXJjZSBBZmZpbml0eSBV
cGRhdGUiLA0KPiAtICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgLyogMEUgKi8gIkhldGVyb2dlbmVvdXMgTWVtb3J5IEF0dHJpYnV0
ZXMgVXBkYXRlIiwNCj4gLSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgIC8qIEFDUEkgNi4yICovDQo+IC0gICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC8qIDBGICovICJFcnJvciBEaXNjb25uZWN0
IFJlY292ZXIiDQo+IC0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgIC8qIEFDUEkgNi4zICovDQo+ICsgICAgICAgWzBdICA9ICJCdXMgQ2hlY2siLA0KPiArICAg
ICAgIFsxXSAgPSAiRGV2aWNlIENoZWNrIiwNCj4gKyAgICAgICBbMl0gID0gIkRldmljZSBXYWtl
IiwNCj4gKyAgICAgICBbM10gID0gIkVqZWN0IFJlcXVlc3QiLA0KPiArICAgICAgIFs0XSAgPSAi
RGV2aWNlIENoZWNrIExpZ2h0IiwNCj4gKyAgICAgICBbNV0gID0gIkZyZXF1ZW5jeSBNaXNtYXRj
aCIsDQo+ICsgICAgICAgWzZdICA9ICJCdXMgTW9kZSBNaXNtYXRjaCIsDQo+ICsgICAgICAgWzdd
ICA9ICJQb3dlciBGYXVsdCIsDQo+ICsgICAgICAgWzhdICA9ICJDYXBhYmlsaXRpZXMgQ2hlY2si
LA0KPiArICAgICAgIFs5XSAgPSAiRGV2aWNlIFBMRCBDaGVjayIsDQo+ICsgICAgICAgWzEwXSA9
ICJSZXNlcnZlZCIsDQo+ICsgICAgICAgWzExXSA9ICJTeXN0ZW0gTG9jYWxpdHkgVXBkYXRlIiwN
Cj4gKyAgICAgICBbMTJdID0gIlJlc2VydmVkICh3YXMgcHJldmlvdXNseSBTaHV0ZG93biBSZXF1
ZXN0KSIsICAvKiBSZXNlcnZlZCBpbiBBQ1BJIDYuMCAqLw0KPiArICAgICAgIFsxM10gPSAiU3lz
dGVtIFJlc291cmNlIEFmZmluaXR5IFVwZGF0ZSIsDQo+ICsgICAgICAgWzE0XSA9ICJIZXRlcm9n
ZW5lb3VzIE1lbW9yeSBBdHRyaWJ1dGVzIFVwZGF0ZSIsICAgICAgLyogQUNQSSA2LjIgKi8NCj4g
KyAgICAgICBbMTVdID0gIkVycm9yIERpc2Nvbm5lY3QgUmVjb3ZlciIgICAgICAgICAgICAgICAg
ICAgICAvKiBBQ1BJIDYuMyAqLw0KPiAgfTsNCj4NCj4gIHN0YXRpYyBjb25zdCBjaGFyICphY3Bp
X2dibF9kZXZpY2Vfbm90aWZ5WzVdID0gew0KPiBAQCAtNTIxLDI2ICs1MTgsMjYgQEAgY29uc3Qg
Y2hhciAqYWNwaV91dF9nZXRfbm90aWZ5X25hbWUodTMyIG5vdGlmeV92YWx1ZSwgYWNwaV9vYmpl
Y3RfdHlwZSB0eXBlKQ0KPiAgICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi8NCj4NCj4gIHN0YXRpYyBj
b25zdCBjaGFyICphY3BpX2dibF9hcmd1bWVudF90eXBlWzIwXSA9IHsNCj4gLSAgICAgICAvKiAw
MCAqLyAiVW5rbm93biBBUkdQIiwNCj4gLSAgICAgICAvKiAwMSAqLyAiQnl0ZURhdGEiLA0KPiAt
ICAgICAgIC8qIDAyICovICJCeXRlTGlzdCIsDQo+IC0gICAgICAgLyogMDMgKi8gIkNoYXJMaXN0
IiwNCj4gLSAgICAgICAvKiAwNCAqLyAiRGF0YU9iamVjdCIsDQo+IC0gICAgICAgLyogMDUgKi8g
IkRhdGFPYmplY3RMaXN0IiwNCj4gLSAgICAgICAvKiAwNiAqLyAiRFdvcmREYXRhIiwNCj4gLSAg
ICAgICAvKiAwNyAqLyAiRmllbGRMaXN0IiwNCj4gLSAgICAgICAvKiAwOCAqLyAiTmFtZSIsDQo+
IC0gICAgICAgLyogMDkgKi8gIk5hbWVTdHJpbmciLA0KPiAtICAgICAgIC8qIDBBICovICJPYmpl
Y3RMaXN0IiwNCj4gLSAgICAgICAvKiAwQiAqLyAiUGFja2FnZUxlbmd0aCIsDQo+IC0gICAgICAg
LyogMEMgKi8gIlN1cGVyTmFtZSIsDQo+IC0gICAgICAgLyogMEQgKi8gIlRhcmdldCIsDQo+IC0g
ICAgICAgLyogMEUgKi8gIlRlcm1BcmciLA0KPiAtICAgICAgIC8qIDBGICovICJUZXJtTGlzdCIs
DQo+IC0gICAgICAgLyogMTAgKi8gIldvcmREYXRhIiwNCj4gLSAgICAgICAvKiAxMSAqLyAiUVdv
cmREYXRhIiwNCj4gLSAgICAgICAvKiAxMiAqLyAiU2ltcGxlTmFtZSIsDQo+IC0gICAgICAgLyog
MTMgKi8gIk5hbWVPclJlZiINCj4gKyAgICAgICBbMHgwMF0gPSAiVW5rbm93biBBUkdQIiwNCj4g
KyAgICAgICBbMHgwMV0gPSAiQnl0ZURhdGEiLA0KPiArICAgICAgIFsweDAyXSA9ICJCeXRlTGlz
dCIsDQo+ICsgICAgICAgWzB4MDNdID0gIkNoYXJMaXN0IiwNCj4gKyAgICAgICBbMHgwNF0gPSAi
RGF0YU9iamVjdCIsDQo+ICsgICAgICAgWzB4MDVdID0gIkRhdGFPYmplY3RMaXN0IiwNCj4gKyAg
ICAgICBbMHgwNl0gPSAiRFdvcmREYXRhIiwNCj4gKyAgICAgICBbMHgwN10gPSAiRmllbGRMaXN0
IiwNCj4gKyAgICAgICBbMHgwOF0gPSAiTmFtZSIsDQo+ICsgICAgICAgWzB4MDldID0gIk5hbWVT
dHJpbmciLA0KPiArICAgICAgIFsweDBBXSA9ICJPYmplY3RMaXN0IiwNCj4gKyAgICAgICBbMHgw
Ql0gPSAiUGFja2FnZUxlbmd0aCIsDQo+ICsgICAgICAgWzB4MENdID0gIlN1cGVyTmFtZSIsDQo+
ICsgICAgICAgWzB4MERdID0gIlRhcmdldCIsDQo+ICsgICAgICAgWzB4MEVdID0gIlRlcm1Bcmci
LA0KPiArICAgICAgIFsweDBGXSA9ICJUZXJtTGlzdCIsDQo+ICsgICAgICAgWzB4MTBdID0gIldv
cmREYXRhIiwNCj4gKyAgICAgICBbMHgxMV0gPSAiUVdvcmREYXRhIiwNCj4gKyAgICAgICBbMHgx
Ml0gPSAiU2ltcGxlTmFtZSIsDQo+ICsgICAgICAgWzB4MTNdID0gIk5hbWVPclJlZiINCj4gIH07
DQo+DQo+ICBjb25zdCBjaGFyICphY3BpX3V0X2dldF9hcmd1bWVudF90eXBlX25hbWUodTMyIGFy
Z190eXBlKQ0KPiAtLQ0KPiAyLjM1LjENCj4KX19fX19fX19fX19fX19fX19fX19fX19fX19fX19f
X19fX19fX19fX19fX19fX18KRGV2ZWwgbWFpbGluZyBsaXN0IC0tIGRldmVsQGFjcGljYS5vcmcK
VG8gdW5zdWJzY3JpYmUgc2VuZCBhbiBlbWFpbCB0byBkZXZlbC1sZWF2ZUBhY3BpY2Eub3JnCiUo
d2ViX3BhZ2VfdXJsKXNsaXN0aW5mbyUoY2dpZXh0KXMvJShfaW50ZXJuYWxfbmFtZSlz
